sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "dev"
env:
  global:
    - SPLIT_BUILD=1
    - COVERAGE=1
    - CACHE_NAME=$TRAVIS_PERL_VERSION
cache:
  directories:
    - .perlbrew/
matrix:
  allow_failures:
    - perl: dev
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
