sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.24"
  - "dev"
env:
  global:
    - COVERAGE=1
matrix:
  allow_failures:
    - perl: dev
before_install:
  - cpanp x
  - eval $(curl https://travis-perl.github.io/init) --auto
